### PR TITLE
Epub3 fixed layout

### PR DESCRIPTION
**Pull request by nono**
Hi, I've added extraction of the properties of epub3 fixed layout on the spine itemrefs.

### CODE REVIEW

**Comment by nono** [comment]
Hi, any news about this pull-request?

**Comment by joseph** [comment]
Apologies, I never saw this pull request for some reason. Taking a look now, thanks.

**Comment by joseph** [comment]
This is a really great contribution. Thanks! I've merged it to master and will endeavour to roll out a Peregrin 1.2 release incorporating these changes and a few others shortly.

**Comment by nono** [comment]
Great :-)

**Pull request merged**
