### PR TITLE
Epub 3.0 : Reading compatibility

### PR DESCRIPTION
**Pull request by klacointe**
Hi,

Here are some fixes related to Epub 3.0 integration into Peregrin (only reading side for now).
- Extract new "Meta Element" (http://idpf.org/epub/30/spec/epub30-publications.html#sec-meta-elem)
- Extract chapters from "Navigation Document" (http://idpf.org/epub/30/spec/epub30-contentdocs.html#sec-xhtml-nav) instead of from OCX file. Keep OCX fallback if "Navigation Document" is missing.

I really appreciate your opinion on these changes.

Thanks for this gem !

### CODE REVIEW

**Comment by joseph** [comment]
Thanks, this is a terrific contribution. Much appreciated.

**Comment by joseph** [comment]
Released as Peregrin 1.1.2. Thanks again.

**Comment by klacointe** [comment]
Hmm, no updates found in release 1.1.2 :/
bad merge ?

**Comment by joseph** [comment]
Oh, thanks, fixed.

**Comment by joseph** [comment]
Er, not quite fixed. I'm kinda hashing this release. I'll yank this one and put another one out after some more testing. :)

**Comment by klacointe** [comment]
ok in 1.1.4, thanks !

**Pull request merged**
